title: AWS DevOps Project Checklist
description: A comprehensive checklist for implementing AWS DevOps best practices with GitHub and Terraform
theme: minima
show_downloads: false
github:
  is_project_page: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge