title: AkujinLuffy Summer Homework
description: AWS DevOps Project Checklist
theme: minima
show_downloads: false
github:
  is_project_page: true
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge